---
title: Alaap
author: Rupsa Ray
---

Hey **Integration**! Rupsa here,

After the massive success of **Band-e-Thlon**, the cultural chapter of 
**Integration** was ready to grace the stage for its singing competition; 
**Alaap**.

This year, the prestigious singing competition was truly a celebration of 
music as we paid tribute to the musical maestro Padma Shri Late **Ustad Rashid 
Khan**. It was a two-day event filled with beautiful melodies and soulful 
performances. The Prelims were held on the *3rd of February* and the Finals on 
the *4th*.

Renowned *Nazrulgeeti* artist *Shrimati Monali Mitra Paladhi* and *Times of 
India's* best male vocalist for **Kishore Kumar** award recipient **Shri 
Surankan Bhowmick** had graced the event by being present as judges for the 
prelims.

We also had the honor to have **Shri Supriya Das Bala**, a known face in 
social media and television as our percussionist to support our participants.

The event started with a brief speech on *Ustad Rashid Khan*, his life, works 
and musical expeditions, followed by a 1-minute silence condoling his tragic 
demise.

It was finally time for the main event to begin!

One of the most captivating aspects of this event was the sheer diversity of 
performances. More than 50 enthusiastic participants from various colleges 
performed solo and duet renditions of songs spanning a variety of genres of 
classical, and *Bollywood* songs, *Rabindra Sangeet*, and *Nazrul Geeti* and 
set the stage on fire with their eclectic tastes and talents.

As the performances came to an end, the top 20 performers were selected to 
compete for the Finals.

On 4th February, the 20 finalists were ready to rock the stage. **Kajal 
Sengupta**, the honorary secretary of "Sarbabharatiya Sangeet o Sankriti 
Parishad" and **Snighdadeb Sengupta**, recipient of *Radio Mirchi Music Award 
Bangla* best male vocalist 2016, honoured the event with their august 
presence as judges for the performances of the finalists. The event began 
with another speech on Late *Ustad Rashid Khan*'s life, after which began the 
final performances to achieve the coveted spots in the top five. As the final 
notes faded into the air, the judges retreated to deliberate, faced with the 
daunting task of selecting the winners from a pool of exceptional talent. 
Each participant, regardless of the outcome, was applauded for their talent 
and dedication. Finally, winners are announced, amidst cheers and applause, a 
testament to the spirit of camaraderie that defines college fests. **Rishiraj 
Baul** won the competition with his flawless rendition of Raga Jog. **Ahana 
Nandy**, **Aishik Bhattacharya**, **Debayani Sinha Ray**, and **Swagnik Sinha Roy** 
were the other top 5 winners in that order. The winners were awarded cash 
prizes from a prize pool of Rs 5000 along with rank certificates. All 20 
finalists were given finalist certificates.

As this year's edition of **Alaap** concluded, it left behind a legacy of 
harmony, resonating in the memories of those who witnessed its magic. It 
serves as a testament to the power of music to transcend barriers, unite 
hearts, and create everlasting bonds. I hope you enjoyed reading about this 
event as much as we enjoyed hosting it. Stay tuned for more exciting 
**Integration** events in the future!

Au revoir.
